# Generated by Django 3.1.7 on 2021-08-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okeadminıu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='İletisimModelForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=170)),
                ('isim_sayisim', models.CharField(max_length=150)),
                ('mesaj', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'İletisim',
                'verbose_name_plural': 'İletişim',
                'db_table': 'iletisim',
            },
        ),
        migrations.CreateModel(
            name='İletısımModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=170)),
                ('isim_soyisim', models.CharField(max_length=150)),
                ('mesaj', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'iletisimForm',
                'verbose_name_plural': 'iletisimForm',
                'db_table': 'iletisimForm',
            },
        ),
    ]
