# Generated by Django 3.1.7 on 2021-08-12 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okeadminıu', '0002_i̇letisimmodelform_i̇letısımmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='İletısımModel',
        ),
        migrations.DeleteModel(
            name='PortfoyloModel',
        ),
    ]
