# Generated by Django 3.1.7 on 2021-08-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okeadminıu', '0003_auto_20210812_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfoyloModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilk_resim', models.ImageField(upload_to='portfoylo_resimleri')),
                ('slider_resim1', models.ImageField(upload_to='portfoylo_resimleri')),
                ('slider_resim2', models.ImageField(upload_to='portfoylo_resimleri')),
                ('slider_resim3', models.ImageField(upload_to='portfoylo_resimleri')),
                ('baslik', models.CharField(max_length=400)),
                ('icerik', models.TextField(max_length=400)),
                ('kategori', models.CharField(max_length=50)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Portfoylo',
                'verbose_name_plural': 'Portfoylo',
                'db_table': 'Portfoylo',
            },
        ),
    ]
